language: ruby
script: erb nginx.conf
deploy:
  edge: true
  provider: cloudfoundry
  username: gsa-18f-federalist_deployer
  password:
    secure: VdLz94qANHAcgTWH3A1SYkWvq9xq1rZjjxvhdPVPGOSXn4uk7C4Mnm6pOFWL5nY7oETurXffrT6yzyfxrWiVzc52j8JNBzo72VVyeYLfURG328q92ZSAYcnpr0bzrJn0XJ4+0ZZj8V2mYMyc+HlAKHZN06A194QiZbBAVVKqHwVGZRHc6nkcxzzpxV+q6iINoqBiYWSfsjxx+fHXnagNBwWRXYz4Gnou1x76vn3Lp+OCe3tgelZR7ziAN0av2RRELULTmE4m79nBfsG0OPN/eJoyewMf+5N4/0tUgKVCivDvmJdz5MIZanRMJkorTQUqCe3HcNCMrVdMU6IpoXCk4SmnhaNNOV9N/M+0EjVohBv3AMiygjJ27qhtLKYdpxM9KgmzD/Cwf/By7mbT/wa4gyTyZ3MnBhhoKpgkNJK1kiga19g8tVoEpkdfrzsYjFiIvZV4I7KUDWy1JKEfSe0+8hBt4whlojCl34MOBGkhDq+VPjM2TxvqBBtr/5/wH3mO+KXftW0WCyxbwocYGiUNoif2m6Pi8xDyLXw43s9Bhq2ZMzPySAamLiAv+XvMOOZFnu6A29aOkUmD1Q/Zm1Eew8iYLF6OtV78HDaL//7m+SAzvjDRmzWF7iI+2fVO2vzQYqWE8gYUpzkvfcAloCswFji1sDGikqi6HmEUAMopNSo=
  api: https://api.fr.cloud.gov
  organization: gsa-18f-federalist
  space: production
  on:
    branch: master
