version: '3'
services:
  build:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      # Used by variable substitution in `parse-conf.js`
      DEDICATED_S3_BUCKET_URL: 'http://mock:$MOCK_PORT/dedicated'
      FEDERALIST_PROXY_SERVER_NAME: 'federalist-proxy-staging'
      FEDERALIST_S3_BUCKET_URL: 'http://mock:$MOCK_PORT/shared'
      HOME: '/usr/share/nginx/html'
      PROXY_PORT: $PROXY_PORT
  mock:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "./bin/mock.js"]
    environment:
      HOST: mock
      PORT: $MOCK_PORT
  nginx:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mock
  app:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      # Determines the url to test against in the test suite
      PROXY_URL: http://nginx:$PROXY_PORT
    depends_on:
      - nginx