version: "2"
services:
  nginx:
    build:
      context: .
    ports:
      - 1338:80
    environment:
      - FEDERALIST_S3_BUCKET_URL=http://cg-f28e32aa-d42e-4906-a813-7d726f69183c.s3-website-us-gov-west-1.amazonaws.com
      - FEDERALIST_PROXY_SERVER_NAME=localhost


