version: 2
jobs:
  prepare:
    environment:
      DEDICATED_S3_BUCKET_URL: 'http://mock:$MOCK_PORT/dedicated'
      FEDERALIST_PROXY_SERVER_NAME: 'federalist-proxy-staging'
      FEDERALIST_S3_BUCKET_URL: 'http://mock:$MOCK_PORT/shared'
      HOME: '/usr/share/nginx/html'
      PROXY_PORT: $PROXY_PORT
    docker:
      image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install      
      - run:
          name: Parse Config
          command: npm run parse-conf
  build:
    machine: true
    steps:
      - run:
          name: Run Tests
          command: docker-compose run app npm test

workflows:
  version: 2
  prepare_and_build:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
