version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Parse Config
          command: docker-compose run build npm run parse-conf
      - run:
          name: Install Dependencies
          command: docker-compose run build npm install
      - run:
          name: Run Tests
          command: docker-compose run app npm test