version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: docker-compose run app npm install
      - run:
          name: Run Tests
          command: docker-compose run app npm test