version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: docker-compose run app npm install
      - run:
          name: Run tests
          command: docker-compose run app npm test