version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: docker-compose run --no-deps app npm install
      - run:
          name: Parse Config
          command: docker-compose run --no-deps app node ./bin/parse-conf.js          
      - run:
          name: Run Tests
          command: docker-compose run app npm test