version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:12
    environment:
      DEDICATED_S3_BUCKET_URL: 'http://mock:$MOCK_PORT/dedicated'
      FEDERALIST_PROXY_SERVER_NAME: 'federalist-proxy-staging'
      FEDERALIST_S3_BUCKET_URL: 'http://mock:$MOCK_PORT/shared'
      PROXY_WWW: '/usr/share/nginx/html'
      PROXY_PORT: $PROXY_PORT
    steps:
      - checkout
      - run:
          name: Parse Config
          command: npm run parse-conf
      - persist_to_workspace:
          root: /
          paths:
            - tmp

  build:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: tmp
      - run: ls -l
      - run: ls -l tmp
      - run:
          name: Run Tests
          command: docker-compose run app

workflows:
  version: 2
  prepare_and_build:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
