version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    environment:
      DEDICATED_S3_BUCKET_URL: 'http://localhost:$MOCK_PORT/dedicated'
      FEDERALIST_PROXY_SERVER_NAME: 'federalist-proxy-staging'
      FEDERALIST_S3_BUCKET_URL: 'http://localhost:$MOCK_PORT/shared'
      PROXY_WWW: '/usr/share/nginx/html'
      PROXY_PORT: $PROXY_PORT
      PROXY_URL: http://localhost:$PROXY_PORT
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Parse Config
          command: npm run parse-conf
      - run:
          name: Run Mock Server
          command: nohup node ./bin/mock.js > output.log &
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run Proxy Server
          command: |
            docker run \
            --mount type=bind,source="$(pwd)"/,target=/usr/share/nginx/html,readonly \
            --mount type=bind,source="$(pwd)"/tmp/nginx.conf,target=/etc/nginx/nginx.conf,readonly \
            --mount type=bind,source="$(pwd)"/mime.types,target=/etc/nginx/mime.types,readonly \
            -p 8000:8000 \
            -d \
            nginx
      - run:
          name: Tun Tests
          command: npm test